import React from 'react';
import { Html } from '@react-three/drei';

const steel = { color: '#71827f', metalness: 0.82, roughness: 0.28 };
const concrete = { color: '#697574', roughness: 0.88, metalness: 0.04 };
const pipe = { color: '#c89b55', metalness: 0.72, roughness: 0.3 };

function Pipe({ position, rotation = [0, 0, Math.PI / 2], length = 1, radius = 0.07, color = '#c89b55' }) { return <mesh castShadow position={position} rotation={rotation}><cylinderGeometry args={[radius, radius, length, 12]} /><meshStandardMaterial {...pipe} color={color} /></mesh>; }
function Gauge({ position, label, active }) { return <group position={position}><mesh rotation-y={Math.PI / 2}><cylinderGeometry args={[0.2, 0.2, 0.07, 20]} /><meshStandardMaterial color="#202a2b" metalness={0.7} /></mesh><mesh position={[0.02, 0, 0.04]} rotation-y={Math.PI / 2}><circleGeometry args={[0.14, 20]} /><meshBasicMaterial color={active ? '#8ae4cc' : '#d1b46c'} /></mesh><Html position={[0, -0.34, 0]} center distanceFactor={12}><div className="micro-label">{label}</div></Html></group>; }
function Stage({ number, label, position, active }) { return <group position={position}><mesh castShadow receiveShadow><boxGeometry args={[1.75, 1.65, 1.45]} /><meshStandardMaterial {...concrete} color={active ? '#587b73' : '#53615f'} /></mesh><mesh position={[0, 0.28, 0.74]}><boxGeometry args={[1.15, 0.48, 0.025]} /><meshStandardMaterial color="#253638" roughness={0.25} metalness={0.35} /></mesh><mesh position={[0, 0.28, 0.76]}><planeGeometry args={[0.93, 0.31]} /><meshBasicMaterial color={active ? '#6edbc6' : '#385b59'} transparent opacity={0.7} /></mesh><mesh position={[0, 0.92, 0]}><boxGeometry args={[1.25, 0.08, 1.05]} /><meshStandardMaterial {...steel} /></mesh><Html position={[0, -1.02, 0]} center distanceFactor={11}><div className={`filter-label ${active ? 'stage-active' : ''}`}><b>{number}</b> {label}</div></Html></group>; }

export function SensorStation({ readings, onSelect }) { return <group position={[3, 0, 0]} onClick={() => onSelect({ title: 'Environmental Sensor Node', body: 'Industrial enclosure with a controlled sample line. All dashboard values are simulated demonstration data.' })}><mesh castShadow position={[0, 1.5, 0]}><boxGeometry args={[1.9, 2.55, 1.25]} /><meshStandardMaterial color="#435252" metalness={0.68} roughness={0.31} /></mesh><mesh position={[0, 1.5, 0.66]}><boxGeometry args={[1.42, 0.92, 0.035]} /><meshStandardMaterial color="#182426" roughness={0.22} /></mesh><mesh position={[0, 1.5, 0.69]}><planeGeometry args={[1.18, 0.66]} /><meshBasicMaterial color="#77ddc9" /></mesh><mesh position={[0, 2.48, 0]}><cylinderGeometry args={[0.11, 0.11, 0.34, 16]} /><meshStandardMaterial color="#e8b75f" emissive="#bb6b27" emissiveIntensity={2} /></mesh><Pipe position={[-1.2, 0.85, 0]} rotation={[0, 0, -0.28]} length={2.2} radius={0.075} /><Pipe position={[0, 0.28, 0]} rotation={[0, 0, 0]} length={1.9} radius={0.06} color="#82c5bb" /><mesh position={[0, 0.16, 0]}><boxGeometry args={[2.35, 0.13, 1.7]} /><meshStandardMaterial {...steel} /></mesh><Gauge position={[-0.62, 2.25, 0.67]} label="pH" active /><Gauge position={[0.05, 2.25, 0.67]} label="NTU" active /><Html position={[0, 3.2, 0]} distanceFactor={9}><div className="world-tag sensor-tag"><span className="pulse-dot" /> SENSOR NODE · ONLINE</div></Html></group>; }

export function SamplingChamber({ onSelect }) { return <group position={[6.2, 0, 0]} onClick={() => onSelect({ title: 'Controlled side-stream testing chamber', body: 'A sealed educational chamber isolates the sample from the urban channel. Students observe through glass and use the instrument panel from the protected deck.' })}><mesh castShadow position={[0, 1.15, 0]}><boxGeometry args={[1.7, 1.65, 1.55]} /><meshStandardMaterial {...steel} color="#62736f" /></mesh><mesh position={[0, 1.25, 0.79]}><boxGeometry args={[1.18, 0.92, 0.035]} /><meshPhysicalMaterial color="#92d5d0" transparent opacity={0.28} roughness={0.12} metalness={0.1} transmission={0.15} /></mesh><Pipe position={[-1.1, 1.15, 0]} length={1.7} radius={0.08} /><Pipe position={[1.1, 0.78, 0]} length={1.7} radius={0.08} /><mesh position={[0, 0.18, 0]}><boxGeometry args={[2, 0.12, 1.8]} /><meshStandardMaterial {...concrete} /></mesh><Html position={[0, 2.25, 0]} distanceFactor={10}><div className="world-tag chamber-tag">CONTROLLED SAMPLING CHAMBER</div></Html></group>; }

export function FiltrationSystem({ progress, onSelect }) { const stages = [['01', 'SCREENING'], ['02', 'SEDIMENTATION'], ['03', 'BIO-FILTRATION'], ['04', 'FINAL FILTRATION']]; return <group position={[-7, 0, 0]} onClick={() => onSelect({ title: 'Four-stage educational filtration demonstration', body: 'A compact teaching skid routes a simulated side-stream through screening, sedimentation, bio-filtration and final filtration.' })}><mesh receiveShadow position={[3.35, 0.42, 0]}><boxGeometry args={[9.5, 0.12, 2.2]} /><meshStandardMaterial {...steel} /></mesh>{stages.map(([number, label], index) => <Stage key={label} number={number} label={label} position={[index * 2.25, 1.28, 0]} active={index < progress / 25} />)}{[0, 1, 2].map((index) => <Pipe key={index} position={[1.1 + index * 2.25, 1.48, 0]} length={1.1} radius={0.065} color="#78cfc2" />)}<Gauge position={[-0.75, 1.9, 0.75]} label="IN" active={progress > 0} /><Gauge position={[7.45, 1.9, 0.75]} label="OUT" active={progress >= 100} /><Html position={[3.35, 3.05, 0]} center distanceFactor={10}><div className="world-tag filtration-tag">EDUCATIONAL PROCESS SKID · 4 STAGES</div></Html></group>; }
